version: '3'

services:
  db:
    image: mysql:5.7
    container_name: CubeDB
    environment:
      MYSQL_ROOT_PASSWORD: KMPCube
      MYSQL_DATABASE: CUBE_KMP
      MYSQL_USER: KMPCube
      MYSQL_PASSWORD: KMPCube
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: CubePMA
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  dbdata: